# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subelsky_enhancements}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Subelsky"]
  s.date = %q{2009-12-29}
  s.description = %q{Various Ruby patches and enhancements I carry from project to project}
  s.email = %q{mike@subelsky.com}
  s.files = [
    ".specification",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "TODO.txt",
     "VERSION",
     "lib/subelsky_enhancements.rb",
     "lib/subelsky_enhancements/hash.rb",
     "subelsky_enhancements.gemspec",
     "test/hash_test.rb"
  ]
  s.homepage = %q{http://github.com/subelsky/enhancements}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Various Ruby patches and enhancements I carry from project to project}
  s.test_files = [
    "test/hash_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

